$path = "c:\Users\memdu\Contacts\JeolojiPusulasi\app.js"
$lines = Get-Content $path
$newContent = @()

# Part 1: Before optimizeMapPoints
# Keep lines 0 to 899 (inclusive headers)
$newContent += $lines[0..899]

# Part 2: New optimizeMapPoints Logic
$newContent += '    // Smart Label Placement (v383 - 8-Way Collision Avoidance)'
$newContent += '    let optimizeTimeout = null;'
$newContent += '    function optimizeMapPoints() {'
$newContent += '        if (optimizeTimeout) clearTimeout(optimizeTimeout);'
$newContent += ''
$newContent += '        optimizeTimeout = setTimeout(() => {'
$newContent += '            // 1. Get all visible KML markers and their tooltips'
$newContent += '            const markers = []; '
$newContent += '            externalLayers.forEach(l => {'
$newContent += '                if (!l.visible || !l.pointsVisible) return;'
$newContent += '                l.layer.eachLayer(layer => {'
$newContent += '                    if (layer instanceof L.Marker && layer.getElement() && layer.getElement().querySelector(".kml-custom-icon")) {'
$newContent += '                        markers.push(layer);'
$newContent += '                    }'
$newContent += '                });'
$newContent += '            });'
$newContent += ''
$newContent += '            if (markers.length === 0) return;'
$newContent += ''
$newContent += '            const mapBounds = map.getBounds();'
$newContent += '            const occupiedRects = []; // Store {top, left, right, bottom} of occupied areas'
$newContent += '            const labelsToPlace = []; // Collect valid labels to process'
$newContent += ''
$newContent += '            // 2. Pre-process markers: Ensure they are visible and visible on map'
$newContent += '            markers.forEach(marker => {'
$newContent += '                const el = marker.getElement();'
$newContent += '                if (!el) return;'
$newContent += ''
$newContent += '                // Always show marker (User Rule: Never hide markers)'
$newContent += '                el.style.display = "block";'
$newContent += '                el.style.opacity = "1";'
$newContent += ''
$newContent += '                const latLng = marker.getLatLng();'
$newContent += '                if (!mapBounds.contains(latLng)) {'
$newContent += '                    // Off-screen optimization'
$newContent += '                    if (marker.getTooltip()) {'
$newContent += '                        marker.closeTooltip();'
$newContent += '                    }'
$newContent += '                    return;'
$newContent += '                }'
$newContent += ''
$newContent += '                // If on screen, ensure tooltip is open/created'
$newContent += '                if (marker.getTooltip()) {'
$newContent += '                    if (!map.hasLayer(marker.getTooltip())) {'
$newContent += '                        marker.openTooltip();'
$newContent += '                    }'
$newContent += '                    const tooltip = marker.getTooltip();'
$newContent += '                    const tooltipEl = tooltip.getElement();'
$newContent += '                    // Add marker rect to occupied list'
$newContent += '                    const markerRect = el.getBoundingClientRect();'
$newContent += '                    occupiedRects.push({'
$newContent += '                        left: markerRect.left,'
$newContent += '                        top: markerRect.top,'
$newContent += '                        right: markerRect.right,'
$newContent += '                        bottom: markerRect.bottom'
$newContent += '                    });'
$newContent += ''
$newContent += '                    if (tooltipEl) {'
$newContent += '                        labelsToPlace.push({ marker, tooltip, tooltipEl, markerRect });'
$newContent += '                    }'
$newContent += '                }'
$newContent += '            });'
$newContent += ''
$newContent += '            // 3. Smart Placement Algorithm'
$newContent += '            // Try 8 positions: Top(N), NE, E, SE, S, SW, W, NW'
$newContent += '            const dist = 12; '
$newContent += '            const positions = ['
$newContent += '                { x: 0, y: -dist }, // N'
$newContent += '                { x: dist, y: -dist }, // NE'
$newContent += '                { x: dist, y: 0 }, // E'
$newContent += '                { x: dist, y: dist }, // SE'
$newContent += '                { x: 0, y: dist }, // S'
$newContent += '                { x: -dist, y: dist }, // SW'
$newContent += '                { x: -dist, y: 0 }, // W'
$newContent += '                { x: -dist, y: -dist } // NW'
$newContent += '            ];'
$newContent += ''
$newContent += '            labelsToPlace.forEach(item => {'
$newContent += '                const { tooltipEl, markerRect } = item;'
$newContent += '                '
$newContent += '                tooltipEl.style.transform = "none"; '
$newContent += '                tooltipEl.style.display = "block"; '
$newContent += '                '
$newContent += '                const width = tooltipEl.offsetWidth;'
$newContent += '                const height = tooltipEl.offsetHeight;'
$newContent += '                const markerCenter = {'
$newContent += '                    x: markerRect.left + markerRect.width / 2,'
$newContent += '                    y: markerRect.top + markerRect.height / 2'
$newContent += '                };'
$newContent += ''
$newContent += '                let bestPos = null;'
$newContent += ''
$newContent += '                for (let i = 0; i < positions.length; i++) {'
$newContent += '                    const offset = positions[i];'
$newContent += '                    '
$newContent += '                    const targetX = markerCenter.x + offset.x; '
$newContent += '                    const targetY = markerCenter.y + offset.y;'
$newContent += ''
$newContent += '                    const candidateRect = {'
$newContent += '                        left: targetX - width / 2,'
$newContent += '                        right: targetX + width / 2,'
$newContent += '                        top: targetY - height / 2,'
$newContent += '                        bottom: targetY + height / 2'
$newContent += '                    };'
$newContent += ''
$newContent += '                    let collision = false;'
$newContent += '                    for (const obst of occupiedRects) {'
$newContent += '                         if (!(candidateRect.right < obst.left || '
$newContent += '                               candidateRect.left > obst.right || '
$newContent += '                               candidateRect.bottom < obst.top || '
$newContent += '                               candidateRect.top > obst.bottom)) {'
$newContent += '                            collision = true;'
$newContent += '                            break;'
$newContent += '                        }'
$newContent += '                    }'
$newContent += ''
$newContent += '                    if (!collision) {'
$newContent += '                        bestPos = { x: offset.x, y: offset.y, rect: candidateRect };'
$newContent += '                        break; '
$newContent += '                    }'
$newContent += '                }'
$newContent += ''
$newContent += '                if (bestPos) {'
$newContent += '                    tooltipEl.style.opacity = "1";'
$newContent += '                    tooltipEl.style.visibility = "visible";'
$newContent += '                    tooltipEl.style.transform = `translate3d(${bestPos.x}px, ${bestPos.y}px, 0)`;'
$newContent += '                    occupiedRects.push(bestPos.rect);'
$newContent += '                } else {'
$newContent += '                    tooltipEl.style.opacity = "0";'
$newContent += '                    tooltipEl.style.visibility = "hidden";'
$newContent += '                }'
$newContent += '            });'
$newContent += ''
$newContent += '        }, 50);'
$newContent += '    }'

# Part 3: Middle section (Resume from line 980 -> Index 979)
# Stop before line 1979 -> Index 1978. So keep until 1977.
$newContent += $lines[979..1977]

# Part 4: New Offset
$newContent += '                    offset: [0, 0], // v383: Start at center, Smart Label will move it'
$newContent += '                    sticky: false // Changed to false for better stability'

# Part 5: Rest of file (Resume from line 1981 -> Index 1980)
$newContent += $lines[1980..($lines.Count-1)]

$newContent | Set-Content $path -Encoding UTF8
Write-Host "Update Complete"
